name: control-plane-console
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com
global:
  platform: "openshift"
  edpName: mdtu-ddm-edp-cicd-control-plane-dev
basePath: ""
projectUrlMask: "/console/project/{namespace}/overview"
imageStreamUrlMask: "/console/project/{namespace}/browse/images/{stream}"

ingress:
  required: true
  site: control-plane-console
  path: /

operator:
  serviceAccountName: control-plane-console
  clusterRoleName: edp-admin-console-operator-clusterrole-mdtu-ddm-edp-cicd

oauthclientName: oauth-admin-console-client
