name: ddm-admin-console
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com
platform: "openshift"

database:
  image: postgres:9.6
  capacity: 2Gi
  storageClass: gp2

ingress:
  required: true
  site: ddm-admin-console
  path: /

image:
  name: ddm-admin-console
  version: latest