apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-console-operator-{{ .Values.namespace }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: edp-admin-console-operator-clusterrole-mdtu-ddm-edp-cicd
  apiGroup: rbac.authorization.k8s.io