apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-{{ .Values.global.edpName }}
roleRef:
  name: edp-{{ .Values.name }}-clusterrole-{{ .Values.global.edpName }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.name }}-edp"
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount::{{ .Values.name }}-edp
groupNames: []
