apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: {{ .Values.name }}
    name: {{ .Values.db.name }}
spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ .Values.db.name }}
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: {{ .Values.db.name }}
        spec:
            containers:
                - name: {{ .Values.db.name }}
                  env:
                      - name: POSTGRES_DB
                        value: {{ .Values.db.name }}
                      - name: POSTGRES_USER
                        value: "admin"
                      - name: POSTGRES_PASSWORD
                        value: "admin"
                      - name: PGDATA
                        value: /var/lib/postgresql/data/pgdata
                      - name: POD_IP
                        valueFrom: { fieldRef: { fieldPath: status.podIP } }
                  image: {{ .Values.db.image }}
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: {{ .Values.db.port }}
                        protocol: TCP
                  livenessProbe:
                      exec:
                          command:
                              - sh
                              - -c
                              - exec pg_isready --host $POD_IP
                      initialDelaySeconds: 60
                      timeoutSeconds: 5
                      failureThreshold: 6
                  readinessProbe:
                      exec:
                          command:
                              - sh
                              - -c
                              - exec pg_isready --host $POD_IP
                      initialDelaySeconds: 60
                      timeoutSeconds: 3
                      periodSeconds: 5
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: {{ .Values.db.name }}
            serviceAccount: {{ .Values.name }}
            volumes:
                - name: {{ .Values.db.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Values.db.name }}