apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.db.name }}
    labels:
        app: {{ .Values.db.name }}
spec:
    ports:
        - name: {{ .Values.db.name }}
          port: 5432
    selector:
        app: {{ .Values.db.name }}
    type: ClusterIP
    sessionAffinity: None