apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  backoffLimit: 25
  template:
    metadata:
      name: db-init
      labels:
        app: {{.Values.db.name}}
    spec:
      restartPolicy: Never
      containers:
        - image: {{.Values.db.image}}
          name: db-init
          command:
            - "/bin/bash"
            - "-c"
            - "psql -h $(PGHOST) -d $(POSTGRES_DB) -U $(POSTGRES_USER) -c 'CREATE SCHEMA IF NOT EXISTS \"$(EDP_NAME)\"; \
              DO \
              $do$ \
              BEGIN \
                 IF NOT EXISTS (SELECT 1 FROM pg_user WHERE usename = '\u005C''\u0027'$(TENANT_ADMIN_USERNAME)'\u005C''\u0027') THEN \
                    CREATE USER \"$(TENANT_ADMIN_USERNAME)\" WITH PASSWORD '\u005C''\u0027'$(TENANT_ADMIN_PASSWORD)'\u005C''\u0027'; \
                 END IF; \
              END \
              $do$; \
              GRANT ALL PRIVILEGES ON SCHEMA \"$(EDP_NAME)\" TO \"$(TENANT_ADMIN_USERNAME)\"';"
          env:
            - name: EDP_NAME
              valueFrom:
                configMapKeyRef:
                  key: edp_name
                  name: edp-config
            - name: POSTGRES_USER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: TENANT_ADMIN_USERNAME
              value: "admin"
            - name: TENANT_ADMIN_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: {{.Values.db.name}}
            - name: PGHOST
              value: {{.Values.db.host}}
      initContainers:
        - image: {{.Values.db.image}}
          name: db-wait
          command:
            - /bin/bash
            - -c
            - while ! pg_isready -d $(POSTGRES_DB) -h $(PGHOST) -U $(POSTGRES_USER)  </dev/null; do echo waiting for edp-install-wizard;
              sleep 10; done;
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: TENANT_ADMIN_USERNAME
              value: "admin"
            - name: TENANT_ADMIN_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: {{.Values.db.name}}
            - name: PGHOST
              value: {{.Values.db.name}}
