{{ $oauthclientSecret := randAlphaNum 16 }}

---
apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  name: admin-console-client
redirectURIs:
  - https://control-plane-console-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/auth/callback
  - http://localhost:8080/auth/callback
secret: {{ if .Values.oauthclientSecret }}{{ .Values.oauthclientSecret }}{{ else }}{{ $oauthclientSecret }}{{ end }}

---

kind: Secret
apiVersion: v1
metadata:
  name: oauth-admin-console-client
data:
  clientId: YWRtaW4tY29uc29sZS1jbGllbnQ=
  secret: {{ if .Values.oauthclientSecret }}{{ b64enc .Values.oauthclientSecret }}{{ else }}{{ b64enc $oauthclientSecret }}{{ end }}
type: Opaque