apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.name }}-db
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.db.capacity | quote }}
    storageClassName: {{ .Values.db.storageClass }}
    volumeMode: Filesystem