kind: Deployment
apiVersion: apps/v1
metadata:
  name: reconciler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reconciler
  template:
    metadata:
      labels:
        name: reconciler
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: reconciler
          command:
            - reconciler
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: reconciler
            - name: PLATFORM_TYPE
              value: openshift
            - name: PG_HOST
              value: "{{ .Values.db.name }}"
            - name: PG_PORT
              value: "{{ .Values.db.port }}"
            - name: PG_DATABASE
              value: "{{ .Values.db.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ddm-console-db
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ddm-console-db
                  key: db_pass
            - name: DB_SSL_MODE
              value: disable
          securityContext:
            allowPrivilegeEscalation: false
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'epamedp/reconciler:v2.5.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      serviceAccount: {{ .Values.operator.serviceAccountName }}
      securityContext:
        runAsNonRoot: true
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600