kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-cluster-mgmt-admin
rules:
  - verbs:
      - list
      - get
      - create
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
  - verbs:
      - list
      - get
      - create
      - patch
      - watch
      - update
    apiGroups:
      - '*'
    resources:
      - codebases/finalizers
      - codebasebranches/finalizers
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
      - codebases/finalizers
      - codebasebranches/finalizers
    resourceNames:
      - cluster-mgmt
  - apiGroups:
      - '*'
    verbs:
      - create
    resources:
      - secrets
  - apiGroups:
      - '*'
    verbs:
      - get
    resources:
      - secrets
    resourceNames:
      - gerrit-project-creator-password
