kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-cluster-mgmt-admin
rules:
  - verbs:
      - list
      - get
      - create
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
    resourceNames:
      - cluster-mgmt
