kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-registry-reader
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches

