apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cp-registry-creator
rules:
  - apiGroups:
      - "v2.edp.epam.com"
    resources:
      - codebases
      - codebasebranches
      - codebases/finalizers
      - codebasebranches/finalizers
    verbs:
      - "*"
  - apiGroups:
      - '*'
    verbs:
      - create
    resources:
      - secrets
  - apiGroups:
      - '*'
    verbs:
      - get
    resources:
      - secrets
    resourceNames:
      - gerrit-project-creator-password