{{ if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  annotations:
    description: "Route for {{ .Values.name }} application"
  labels:
    app: {{ .Values.name }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  host: {{ .Values.name }}-{{ .Values.namespace }}.{{ .Values.dnsWildcard }}
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
  {{ end }}
